=== albertopaez/javaXML/ejercicio1/bin/centrosprofes.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.w3schools.com" xmlns="http://www.w3schools.com" elementFormDefault="qualified">
<xs:complexType name="Profesor">
    <xs:sequence>
      <xs:element name="codigoprofesor" type="xs:string"/>
      <xs:element name="nombreprofesor" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="Profesores">
    <xs:sequence>
      <xs:element name="profesor" type="Profesor" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="Centro">
    <xs:sequence>
      <xs:element name="codigocentro" type="xs:string"/>
      <xs:element name="nombrecentro" type="xs:string"/>
      <xs:element name="director" type="Profesor"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="Datoscentro">
    <xs:sequence>
      <xs:element name="centro" type="Centro"/>
      <xs:element name="profesores" type="Profesores"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="datoscentro" type="Datoscentro"/>
  </xs:schema>

=== albertopaez/javaXML/ejercicio1/src/micentro.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:datoscentro xmlns:p="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3schools.com centrosprofes.xsd ">
  <p:centro>
    <p:codigocentro>123456789</p:codigocentro>
    <p:nombrecentro>Salesianas Maria Auxiliadora</p:nombrecentro>
    <p:director>
      <p:codigoprofesor>12345</p:codigoprofesor>
      <p:nombreprofesor>Paco</p:nombreprofesor>
    </p:director>
  </p:centro>
  <p:profesores>
    <p:profesor>
      <p:codigoprofesor>12345</p:codigoprofesor>
      <p:nombreprofesor>Paco</p:nombreprofesor>
    </p:profesor>
    <p:profesor>
      <p:codigoprofesor>12745</p:codigoprofesor>
      <p:nombreprofesor>Manolo</p:nombreprofesor>
    </p:profesor>
    <p:profesor>
      <p:codigoprofesor>17345</p:codigoprofesor>
      <p:nombreprofesor>Antonio</p:nombreprofesor>
    </p:profesor>
  </p:profesores>
</p:datoscentro>
